import { Menu } from '../types'

const KOREAN: Menu[] = [
  { name: '불고기', weight: 94 },
  { name: '김치찌개', weight: 93 },
  { name: '된장찌개', weight: 92 },
  { name: '제육볶음', weight: 91 },
  { name: '칼국수', weight: 90 },
  { name: '냉면', weight: 89 },
  { name: '김밥', weight: 88 },
  { name: '국밥', weight: 88 },
  { name: '부대찌개', weight: 87 },
  { name: '순두부찌개', weight: 86 },
  { name: '비빔밥', weight: 85 },
  { name: '떡볶이', weight: 85 },
  { name: '라면', weight: 85 },
  { name: '보쌈', weight: 85 },
  { name: '족발', weight: 85 },
  { name: '갈비탕', weight: 84 },
  { name: '잡채', weight: 83 },
  { name: '볶음밥', weight: 82 },
  { name: '해물파전', weight: 81 },
  { name: '고등어조림', weight: 80 },
  { name: '감자탕', weight: 78 },
  { name: '쌈밥', weight: 75 },
  { name: '덮밥', weight: 75 },
  { name: '죽', weight: 75 },
  { name: '수육', weight: 73 },
  { name: '갈치조림', weight: 71 },
  { name: '매운탕', weight: 70 },
  { name: '곱창', weight: 70 },
  { name: '닭갈비', weight: 69 },
  { name: '오징어볶음', weight: 64 },
  { name: '육개장', weight: 63 },
  { name: '닭곰탕', weight: 61 },
  { name: '닭볶음탕', weight: 60 },
  { name: '잔치국수', weight: 57 },
  { name: '알밥', weight: 56 },
]

export default KOREAN
